"""initial schema

Revision ID: 467aceff9ba0
Revises:
Create Date: 2026-08-09 02:59:22.386279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "467aceff9ba0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("repository", sa.String(length=255), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("base_sha", sa.String(length=64), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("base_ref", sa.String(length=255), nullable=False),
        sa.Column("head_ref", sa.String(length=255), nullable=False),
        sa.Column("html_url", sa.String(length=1000), nullable=False),
        sa.Column("diff", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pull_requests_number"), "pull_requests", ["number"], unique=False)
    op.create_index(
        op.f("ix_pull_requests_repository"), "pull_requests", ["repository"], unique=False
    )
    op.create_table(
        "review_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pull_request_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "awaiting_approval",
                "approved",
                "rejected",
                "failed",
                name="reviewstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "overall_decision",
            sa.Enum("pass_review", "needs_work", "blocked", name="decision"),
            nullable=True,
        ),
        sa.Column("alignment_score", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=1000), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_sessions_pull_request_id"),
        "review_sessions",
        ["pull_request_id"],
        unique=False,
    )
    op.create_index(op.f("ix_review_sessions_status"), "review_sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_review_sessions_trace_id"), "review_sessions", ["trace_id"], unique=False
    )
    op.create_table(
        "agent_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("agent_role", sa.String(length=80), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "passed", "warning", "failed", "skipped", name="taskstatus"
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_tasks_agent_role"), "agent_tasks", ["agent_role"], unique=False)
    op.create_index(op.f("ix_agent_tasks_session_id"), "agent_tasks", ["session_id"], unique=False)
    op.create_table(
        "human_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_decisions_session_id"), "human_decisions", ["session_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_human_decisions_session_id"), table_name="human_decisions")
    op.drop_table("human_decisions")
    op.drop_index(op.f("ix_agent_tasks_session_id"), table_name="agent_tasks")
    op.drop_index(op.f("ix_agent_tasks_agent_role"), table_name="agent_tasks")
    op.drop_table("agent_tasks")
    op.drop_index(op.f("ix_review_sessions_trace_id"), table_name="review_sessions")
    op.drop_index(op.f("ix_review_sessions_status"), table_name="review_sessions")
    op.drop_index(op.f("ix_review_sessions_pull_request_id"), table_name="review_sessions")
    op.drop_table("review_sessions")
    op.drop_index(op.f("ix_pull_requests_repository"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_number"), table_name="pull_requests")
    op.drop_table("pull_requests")
    # ### end Alembic commands ###
