apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app.kubernetes.io/name: pr-agent
    app.kubernetes.io/component: api
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  selector:
    app.kubernetes.io/name: pr-agent
    app.kubernetes.io/component: web
  ports:
    - port: 3000
      targetPort: 3000

